################ Portugues language ##################
[pt]
languageName = "Pt"
languageCode = "pt-br"
contentDir = "content/portugues"
weight = 1

################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1